### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by hanranti** [samhareem/MatrixCalc#2]
# Koodikatselmointi

Projekti ladattu 19.6 klo 18.29

Koodi oli selkeää ja hyvin kommentoitu myös private metodeissa, mikä helpotti ohjelman ymmärtämistä. Ohjelman luokkarakenne on myös ihan järkevä.

Testejä on kattavasti ja kaikki menevät läpi.

Toimiiko determinantin laskeminen oikein? Ohjelma antaa ensimmäisen matriisin determinantiksi 64862.4375, mutta saan esimerkiksi näillä laskimilla https://matrixcalc.org/en/det.html, http://matrix.reshish.com/detCalculation.php arvoksi -26109.

Saan myös käänteismatriisista eri tuloksen tällä laskimella http://matrix.reshish.com/inverCalculation.php.

**Comment by samhareem** [comment]
Hyvin valkattu, tämän siitä saa kun vaan nopeasti testaa parilla eri syötteellä. 

Tuo determinantin laskuvirhe johtuu bugista rivinvaihdossa, minkä onneksi pitäisi olla helppo fiksata. Koitan saada sen pushattua jo tänään gittiin. Tuota käänteismatriisia pitää selvitellä vähän enemmän, mutta toivon että senkin saa pienellä muutoksella korjattua.
